version: '8.3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - "9090:9090"
    volumes:
    - prometheus_data:/etc/prometheus/
    networks:
    - promnet1
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
volumes:
  prometheus_data:
networks:
  promnet1:
    driver: bridge
